### ISSUE TITLE
Information about manual Steps after some updates

### ISSUE THREAD

**Issue by TobiasKoller** [h3xp/RickDangerousUpdate#100]
I accidentally read a post on discord the other day about manual steps to do after some updates.
Not quite sure what the steps were or after which updates I "have" to add them.

It would be nice to have a information-page directly in the tool where it shows you what to do after certain updates were installed.

**Comment by mrludo001** [comment]
I keep thinking that this sort of information is actually better handled via the Discord server.

My reasoning is as follows:

1. When there is a problem found with an update is is usually detected quickly and can often actually be detected by someone who is not able to modify the update tool.
2. For this information to be timely, a release would need to be done and it may not be convenient to do a release.

I would propose that we should put a reference to the Discord server and perhaps have a pointer to a Known Update Issues channel which can have a clear list of caveats and fixes.

**Comment by TobiasKoller** [comment]
I'm ok with that. We should have a dedicated list for that.

**Comment by mrludo001** [comment]
I have added a Support menu item that shows the links to the Discord server and this project page.
