### ISSUE TITLE
Reword or rework Fix Known Bugs to suit RPE image release

### ISSUE THREAD

**Issue by mrludo001** [h3xp/RickDangerousUpdate#114]
Determine if rewording Fix Known Bugs is enough to make Rick happy.

Rick requested this in dev chat...

> I have a some change requests for the update tool before making my final backup.
> - In the Main Menu can we remove (2) Fix Known Bugs
> - Miscellaneous Rename to Tools or System Tools
> - Fix Known bugs rename to Reset Permissions and move to Tools/System Tools

**Comment by LizardWiz** [comment]
I called the menu "System Tools and Utilties", I could go with something else though...

**Comment by mrludo001** [comment]
I commented out the now defunct bugs_dialog function.
