### ISSUE TITLE
Add a test to Installation -> Install option to switch to Update if update_tool.ini exists

### ISSUE THREAD

**Issue by mrludo001** [h3xp/RickDangerousUpdate#125]
Some users appear to not understand the difference between Install and Update and therefore end up removing their installation history.

This could be avoided in one of two ways:

1. Supress the Install option if the tool is already installed so the user would have to uninstall it.
2. Test for the existence of INSTALLED_UPDATES content and warn the user strenuously that they are about to delete their installation history.

**Comment by LizardWiz** [comment]
Maybe we just update if the directory/ini file exists?

**Comment by mrludo001** [comment]
I think that would be a very good solution.
