### ISSUE TITLE
Suggestion. Have an option to allow user to install manually downloaded updates without internet connection.

### ISSUE THREAD

**Issue by gmentzik** [h3xp/RickDangerousUpdate#128]
Sometimes it would be useful to have an option to allow user to install manually downloaded updates without needing internet connection (eg connection is failing for whatever reason). Of course this will come with a disclaimer that it's users responsibility to have installed the most recent update tool version and to have correct/most recent update files. At next connection tool can crosscheck against MEGA folder to validate applied updates.

**Comment by mrludo001** [comment]
I would be against this for the following reasons:

1. The integrity of the tool and image is maintained by the online check for validity of an update before it is applied. It would not be a good situation if the update needs to be undone for some reason.  The tool does provide a mechanism for reversing an update but but this is a last resort approach and in the case of a broken update file this may fail.
2. The information stored in the INSTALLED_UPDATES entry for an update is derived from the information on MEGA. This would not be guaranteed to be valid in the case being described.
3. This potentially adds to the burden of support volunteers having to deal with diagnosing mishaps.
4. There is nothing to stop a user manually applying an update if they chose to do so irrespective of using the update tool. It is incumbent on users doing this to deal with any issues they create for themselves.

I would like to hear the opinions of the other development team members regarding this suggestion.

**Comment by mrludo001** [comment]
This relates to #126

**Comment by WolfRevo** [comment]
> I would be against this for the following reasons:
> 
>     1. The integrity of the tool and image is maintained by the online check for validity of an update before it is applied. It would not be a good situation if the update needs to be undone for some reason.  The tool does provide a mechanism for reversing an update but but this is a last resort approach and in the case of a broken update file this may fail.
> 
>     2. The information stored in the INSTALLED_UPDATES entry for an update is derived from the information on MEGA. This would not be guaranteed to be valid in the case being described.
> 
>     3. This potentially adds to the burden of support volunteers having to deal with diagnosing mishaps.
> 
>     4. There is nothing to stop a user manually applying an update if they chose to do so irrespective of using the update tool. It is incumbent on users doing this to deal with any issues they create for themselves.
> 
> 
> I would like to hear the opinions of the other development team members regarding this suggestion.

I fully agree. All ideas running through my mind how this could work end up in possible unseen situations causing issues we don't want to introduce to the tool and image.
