### ISSUE TITLE
Move INSTALLED_UPDATES out of update_tool.ini

### ISSUE THREAD

**Issue by LizardWiz** [h3xp/RickDangerousUpdate#131]
Put into an ini file named after the mega_dir.

This will allow us to elegantly switch between base versions.

**Comment by LizardWiz** [comment]
Also:
update install.py to move to file if INSTALLED_UPDATES exists in update_tool.ini.
update update.py to create the ini file, if it does not exist.

**Comment by LizardWiz** [comment]
/opt/retropie/configs/all/emulationstation/scripts/system-select/update_notification.sh also needs to be changed, it is written in install.py

**Comment by mrludo001** [comment]
This actually brings it very close to being able to have a 1TB/2TB toggle ...

**Comment by mrludo001** [comment]
update install.py to move to file if INSTALLED_UPDATES exists in update_tool.ini - DONE
update update.py to create the ini file, if it does not exist - DONE
update_notification.sh also needs to be changed, it is written in install.py - DONE
