### ISSUE TITLE
Consider rework of which menus operations return to

### ISSUE THREAD

**Issue by mrludo001** [h3xp/RickDangerousUpdate#142]
A user has suggested that some operations should return to sub-menus rather than the main menu.

**Comment by mrludo001** [comment]
Gamelist check always jumps back to top level menu instead of one level back.

**Comment by mrludo001** [comment]
Fixing this will be a major exercise in cleaning out the madness of recursive menu function calls.

**Comment by LizardWiz** [comment]
I have an idea, let' wrap everything after a check for CANCEL, for dialogs that we want to return to. the last thing that will happen in if not CANCEL is the dialog will call itself again. If not, it will return.

**Comment by mrludo001** [comment]
I was thinking more like this for where recursion is not needed for state retention ...

```
def random_dialog():

    while(True):
         code, tag = d.somefunc(text=dialog_text,
                             choices=menu_choices,
                             extra_button=True, 
                             extra_label="Skip", 
                             title="Cool Title")

        if code == d.OK:
            // do good things

        if code == d.CANCEL:
            break

    return
```

**Comment by mrludo001** [comment]
Changes can be made when convenient.
