### ISSUE TITLE
Install/Update cores

### ISSUE THREAD

**Issue by LizardWiz** [h3xp/RickDangerousUpdate#154]
Will start with bin only

Here are the required commands:
sudo /home/pi/RetroPie-Setup/retropie_packages.sh lr-mupen64plus-next depends
sudo /home/pi/RetroPie-Setup/retropie_packages.sh lr-mupen64plus-next install_bin

Check for retropie.pkg file, date > local date.

I guess we should have a config setting to automatically update the cores (false or bin, leaving the option for src later on)...

**Comment by mrludo001** [comment]
Tested. Works fine.
