### ISSUE TITLE
MS DOS C&C Red Allert - message about inserting the Aftermath disc

### ISSUE THREAD

**Issue by Grassinix** [h3xp/RickDangerousUpdate#197]
Hi, 
when starting NEW MISSIONS I got a message about inserting the Aftermath disc - clicking OK did nothing, and when I pressed cancel the game shut down.
How to solve the problem? 
Thanks for your help!
![20230809_132904](https://github.com/h3xp/RickDangerousUpdate/assets/91186628/bcc0cd9c-9f7d-4146-87f6-9747ddb3a692)

**Comment by mrludo001** [comment]
Hi.  This github project is actually for the update tool of the Rick Dangerous image.  It is not the right place to ask for help on actually using the image.

Please join Rick's Discord server here https://discord.gg/8ghb8DXE the right place to ask this question is here https://discord.gg/9zBantQx .
