### ISSUE TITLE
PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by andku85** [h3xp/RickDangerousUpdate#200]
Before anyone ask. Yes I have used the Reset Permissions and I am still getting this error. I am attaching the error from exceptions.log

So i ssh and sudo delete the file. Now I am getting a could not create issue. 

Please help. also i have very basic linux skills. so more detailed instructions the better.

Thank you

[exception.log](https://github.com/h3xp/RickDangerousUpdate/files/12398439/exception.log)

**Comment by mrludo001** [comment]
Can you please clarify the following for us:

1. The latest version of update_tool is 2.7.6 . What version of the update_tool are you running ?
2. Which update are you trying to apply ?
3. What method are you using to update ?  Are you using the automatic download and install option or a manual download and then install ?

Please execute the following commands, capture their output and attach it to this issue for me:

 ls -l /opt
 ls -l /opt/retropie
 ls -l /opt/retropie/libretrocores/
 ls -l /opt/retropie/libretrocores/lr-mupen64plus-next

I ran those commands on my system and their output is in the attached file.
[lsout.txt](https://github.com/h3xp/RickDangerousUpdate/files/12404036/lsout.txt)

Can you see any obvious difference ?

It may be worthwhile relocating this discussion to the support_update-tool channel on the RD Discord so you get more timely help.  https://discord.gg/9dxc4bhr

**Comment by andku85** [comment]
Thanks for the discord. And it was some help. I figured out how to update the updater. and after updating from 2.5.12 to 2.7.6 it got pass the update issue. 

But i will let you know what my update was doing. 
using the auto update
I installed 1 and 2, then i skipped 3-11(PSX), installed 12-37, skipped 38-40(Sega Saturn), installed 41, got stuck on "Update 042 N64 Emulator.zip (804 B)". i skipped the big ones due to 5gb cap. i will go back and install those. soon and then continue normally.

**Comment by mrludo001** [comment]
Hi,

Processing the updates out of order can lead to problems. I would suggest
that you have a look at using the manual download approach which allows you
to get a bit more creative in bypassing the 5GB download limit.
The limit is done based on IP address so if you have a VPN client on your
PC it is possible to use that to change where you are seen to be
downloading from.
Have a look at this series of posts on the Discord server to see how to
approach this
https://discord.com/channels/857515631422603286/1039490332146020382/1101420079322779729

Some users sign up to Mega for a short period of time to get the majority
of the updates downloaded with less restrictions.

-- Dave

**Comment by andku85** [comment]
I will look into that but what is the url for Retro Power Edition Updates folder on MEGA? i cannot find that on the discord

**Comment by mrludo001** [comment]
Hi,

Look inside the configuration file /home/pi/.update_tool/update_tool.ini
The URL is recorded in update_dir .

If you do not find it, I can send it when I get home later today.

-- Dave

**Comment by andku85** [comment]
ty. i am all set now.

**Comment by mrludo001** [comment]
Ok. I am glad to hear it. I will close the issue now.

-- Dave
