### ISSUE TITLE
Rick puts experimental emulators on the build, they are not in the retropie repo.

### ISSUE THREAD

**Issue by LizardWiz** [h3xp/RickDangerousUpdate#201]
Treat /opt/retropie/libretrocores/ the same as etc/emulationstation/ in process_improvement, add in check_root.

**Comment by LizardWiz** [comment]
This method of adding (or updating) cores only works for libretrocores as for some reason redream/daphne emulator directories are not owned by root. This may be a problem inherent to the build itself, will check.

**Comment by mrludo001** [comment]
Feature added by @LizardWiz tested by @mrludo001 . Released as v2.8.0
