### ISSUE TITLE
bash command from readme.MD not working for 1.0.1 branch aka. v2.0.0

### ISSUE THREAD

**Issue by h3xp** [h3xp/RickDangerousUpdate#21]
The bash command for easy installation from the reademe:
`bash <(curl 'https://raw.githubusercontent.com/h3xp/RickDangerousUpdate/main/install.sh' -s -N) [link]`
does not work. It throws error: 
`/dev/fd/63: line 1: 404:: command not found`

**Comment by h3xp** [comment]
the install.sh takes two arguments but only one is explained in readme.md, the install.sh can propably just be removed

**Comment by LizardWiz** [comment]
This is because install.sh is not in the main branch yet. I only put that main in there to point towards the command once we merge changes into main. I will change the readme to reflect the current v1.0.1 branch for the time being, we will need to change it back to main when we release v2.0.0...

**Comment by h3xp** [comment]
we should get rid of the install.sh as it does nothing but calling the install.py which we can call from the update.py aswell. The install.sh has no use.
