### ISSUE TITLE
Reboot message in dialog is not displayed correctly

### ISSUE THREAD

**Issue by h3xp** [h3xp/RickDangerousUpdate#23]
After applying updates the system reboots automatically.
The message saying so does not get displayed correctly. It only shows "R" instead of "Rebooting in 5 seconds!"

![grafik](https://user-images.githubusercontent.com/24591381/189075520-71bba170-6063-4e6e-b774-9b1695360407.png)

**Comment by LizardWiz** [comment]
I just simplified the reboot message to not show the updates that were installed...

**Comment by h3xp** [comment]
Made it look a little better, closed for now
