### ISSUE TITLE
check wrong permissions function is wrong

### ISSUE THREAD

**Issue by h3xp** [h3xp/RickDangerousUpdate#24]
the check wrong permissions function is checking a wrong directory/file for wrong permissions. 
This only needs the correct path to work correctly. 
We need to ask someone who did not fix the permissions yet which file is wrong.

**Comment by h3xp** [comment]
reopened because people still run into issues with wrong permissions, so this check might not be working? or they just ignore the "warning". double checking this on a fresh installation

**Comment by LizardWiz** [comment]
Reopened: in certain instances "pi pi" is not returned
