### ISSUE TITLE
show "update available" when there is an update available in the main menu

### ISSUE THREAD

**Issue by h3xp** [h3xp/RickDangerousUpdate#28]
title is self explanatory, this relates to #27 
just add an "update available" text behind the current version if there is a newer version available

**Comment by Maniac-uk** [comment]
would be good to have a marker letting you know what version of the script is running?

**Comment by h3xp** [comment]
> would be good to have a marker letting you know what version of the script is running?

Yes, we also thought so, we have #27 for that :)
