### ISSUE TITLE
Clean Auto-Cleans on Bad Roms

### ISSUE THREAD

**Issue by LizardWiz** [h3xp/RickDangerousUpdate#44]
If the image/video is used in a previous gamelist entry, the file will be removed from supporting_files(i.e. directory of snaps/boxart), and it will not be counted as a found file...
Since the rom is not found, when the image/video file do not appear in found_files, it is auto cleaned.

process_supporting files:
    # delete validated files
    if len(file) > 0:
        if file in supporting_files:
            if file not in found_files:
                found_files.append(file)
            index = supporting_files.index(file)
            **del supporting_files[index]**

process_gamelist:
            # check for auto gamelist removal
            if len(found_files) == 0:
                if rom_file not in remove_entries:
                    remove_entries.append(rom_file)

    # remove entry that shouldn't be there
    for entry in remove_entries:

**Comment by WolfRevo** [comment]
Integrated and tested.
