### ISSUE TITLE
Clean gamelists processes orphaned m3u files incorrectly

### ISSUE THREAD

**Issue by LizardWiz** [h3xp/RickDangerousUpdate#53]
Process orphaned files puts all files supposed to be in .data folder into a single file called .data in roms directory.

You can't undo these changes

shutil.move(file_path, dir_backup)
needs to be changed to:
if not os.path.exists(dir_backup):
    os.makedirs(dir_backup)
shutil.move(file_path, dir_backup)

**Comment by WolfRevo** [comment]
Integrated and tested.
