### ISSUE TITLE
RFE: Ability to clear all selected updates OR remembering which updates have been installed already

### ISSUE THREAD

**Issue by thefunkygibbon** [h3xp/RickDangerousUpdate#58]
When doing an updates and you run out of MEGA storage limits you have to re-run the script and omit the large ones (glad you can now see the sizes in the latest update of the script).   you need to go through and uncheck all of the ones you have already installed. which if you're quite far down the 70+ list of updates can be a bit of a faff.

thanks

**Comment by LizardWiz** [comment]
The tool already remembers which updates have been applied, please use the installation option.
