### ISSUE TITLE
Configuration file entry for default manual update directory ?

### ISSUE THREAD

**Issue by mrludo001** [h3xp/RickDangerousUpdate#59]
Just wondering if support for a default manual update directory could be added into update_tool.ini ?

Perhaps this could be recorded after first use of manual updating and then defaulted on subsequent use.

**Comment by WolfRevo** [comment]
[New branch for next version 2.4.0](https://github.com/h3xp/RickDangerousUpdate/tree/v2.4.0)

I integrated an automatic saving the latest used download directory as default for the dialog. This makes it as easy as pressing the button once more to choose the default directory for updating. This will be part of the next release but you can start testing it for sure.

**Comment by mrludo001** [comment]
Works just fine.

**Comment by mrludo001** [comment]
Just noticed that if you use the delete option it clobbers the directory too.  If the path is retained then the directory probably should be as well. My intent with this idea was to always use the same location for manual update files.

**Comment by LizardWiz** [comment]
Ok. We previously just deleted the directory if it was not empty. That was prior to saving the setting in the ini. I guess now that we are saving the last path we should not delete it. 

FYI. I have an .updates folder, where I have all of the updates, and a .single_updates folder where I put one offs.

We will take out the deletion of the directory in the next x.X.x version, unless the testers want to add it to our x.x X version coming out today. The change is simple.

**Comment by mrludo001** [comment]
It works perfectly now. Thanks very much.
