### ISSUE TITLE
Enable all in system overlays, no work

### ISSUE THREAD

**Issue by KeeperSt** [h3xp/RickDangerousUpdate#62]
Enable all in system overlays, no work

![rasp21](https://user-images.githubusercontent.com/31771827/200122443-697552d1-b42c-4e24-a17a-9b7c456452b5.jpg)
![rasp22](https://user-images.githubusercontent.com/31771827/200122465-38b7955d-8982-48e8-b15f-249a3b47956c.jpg)
![rasp23](https://user-images.githubusercontent.com/31771827/200122486-09771d5d-0374-425d-bf24-89a624ce50d6.jpg)
![rasp24](https://user-images.githubusercontent.com/31771827/200122506-89f22275-231e-4093-b169-197c672f5c5f.jpg)
![rasp25](https://user-images.githubusercontent.com/31771827/200122546-0762536f-ccf4-402f-ab44-a7b6a11699f6.jpg)
![rasp26](https://user-images.githubusercontent.com/31771827/200122570-1d3bd243-6622-4a22-a08b-ce8653c35fe5.jpg)

**Comment by WolfRevo** [comment]
Fixed and tested. Will be released with v.2.3.1
