### ISSUE TITLE
Clean emulators.cfg file

### ISSUE THREAD

**Issue by LizardWiz** [h3xp/RickDangerousUpdate#67]
Order it for easy reading, de-duping in the process (if it is possible).

Just load into a list, checking if exists first, then sort.
Edited: I am checking if you can have multiples in there, if so then I guess use a dictionary. This will default to the last entry (i.e. emulator defined).
Overwrite the cfg file.

**Comment by LizardWiz** [comment]
Dupes are allowed, processing with dictionary.

**Comment by mrludo001** [comment]
Tested ... works fine.

**Comment by h3xp** [comment]
fixed in 2.4.0
