### ISSUE TITLE
Sort game lists

### ISSUE THREAD

**Issue by LizardWiz** [h3xp/RickDangerousUpdate#68]
Sort gamelist.xml files by lower() of game name + rom name.
Needs to be both because there are 3 games in there with the same name:
amiga - Fire & Ice: The Daring Adventures of Cool Coyote
arcade - Ketsui: Kizuna Jigoku Tachi
zxspectrum - Gunfright

**Comment by mrludo001** [comment]
Tested and works fine.

**Comment by h3xp** [comment]
fixed in 2.4.0
