### ISSUE TITLE
Update available notification

### ISSUE THREAD

**Issue by h3xp** [h3xp/RickDangerousUpdate#70]
Maybe we can implement a pop-up widget inside of emulation station to show whenever a new improvement is available.
This could be checked periodically or just once at boot.

**Comment by mrludo001** [comment]
An issue requesting being able to trigger a pop up message in emulation station from a shell script was added to the Emulation Station github in April 2021. No action seen on this subsequently. It is issue number 841.

**Comment by h3xp** [comment]
815f78697236baa662268e14a9f820451e01f836

**Comment by mrludo001** [comment]
Notification functionality is relocating into update.py .
An extra command line parameter (notify) will be passed to update.py by /usr/bin/update_tool if provided to it.

**Comment by mrludo001** [comment]
Ready for team testing.

**Comment by mrludo001** [comment]
Remembered to remove cron job processing.

**Comment by mrludo001** [comment]
Notification is now done by calling **update_tool notify** in emulationstation's **autostart.sh** .

Option **notification_timeout = 60** has been added to update_tool.ini to support a changeable timeout during autostart.
Option **start_update_check = False** has been added to update_tool.ini to support a user being able to always check for game updates when starting the tool.

A command line parameter **check** has been added to allow the user to check for game updates.
