### ISSUE TITLE
weird menu behaviour

### ISSUE THREAD

**Issue by h3xp** [h3xp/RickDangerousUpdate#71]
canceling a reinstallation after not selecting updates will display the "no updates selected" screen.
steps to reproduce:

1. click "Load improvements"
2. click "Download and Install updates"
3. cancel out of the menu using the "cancel" button at the bottom
4. click on "Installation"
5. click on "Install/Reinstall"
6. Select "No" when asked to continue.

after that you get a "no updates selected" message and are back in the improvements selection 

instead it should just exit gracefully back to main menu

**Comment by LizardWiz** [comment]
This is fixed
