### ISSUE TITLE
tool_ver not updating correctly

### ISSUE THREAD

**Issue by h3xp** [h3xp/RickDangerousUpdate#72]
I updated to version 2.4.0 by changing the branch in the .ini file.
It did not set the tool_ver variable to 2.4.0 but it set it to 2.3.1 which is the latest main-branch release at the moment.
I have all the features of 2.4.0 on my system though

**Comment by LizardWiz** [comment]
It does this so when we go back to main it recognizes the new update is ready. 

If it is not pointing to main:
- It gets the latest release version from main
- It tells you the version in the ini file (in parentheses)
- It also tells you which branch you are running from (in parenthesis)
